export const GET_HOT_COLLECTION = 'GET_HOT_COLLECTION';
export const GET_HOT_COLLECTION_FAILURE = 'GET_HOT_COLLECTION_FAILURE';


export const GET_BANNER_LIST = 'GET_BANNER_LIST';
export const GET_BANNER_LIST_FAILURE = 'GET_BANNER_LIST_FAILURE';

export const GET_LOGIN_DATA = 'GET_LOGIN_DATA';

export const GET_REGISTER_DATA = 'GET_REGISTER_DATA';
export const GET_REGISTER_DATA_LOAD = 'GET_REGISTER_DATA_LOAD';



export const GET_CAROUSEL_TAG_START = 'GET_CAROUSEL_TAG_START';
export const GET_LISTING_TAG_START = 'GET_LISTING_TAG_START';

export const GET_ERRORS = 'GET_ERRORS';

export const GET_CAROUSEL_TAG = 'GET_CAROUSEL_TAG';
export const GET_LISTING_TAG = 'GET_LISTING_TAG';
export const GET_CAROUSEL_TAG_FAILURE = 'GET_CAROUSEL_TAG_FAILURE';
export const GET_LISTING_TAG_FAILURE = 'GET_LISTING_TAG_FAILURE';


export const GET_BIG_DEALS = 'GET_BIG_DEALS';
export const GET_BIG_DEALS_FAILURE = 'GET_BIG_DEALS_FAILURE';


export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const GET_PRODUCTS_LIST_FAILURE = 'GET_PRODUCTS_LIST_FAILURE';


export const GET_WISHLIST_SELECT = 'GET_WISHLIST_SELECT';

export const GET_PRODUCTS_DETAIL = 'GET_PRODUCTS_DETAIL';
export const GET_PRODUCTS_DETAIL_LOADING = 'GET_PRODUCTS_DETAIL_LOADING';
export const GET_PRODUCTS_DETAIL_FAILURE = 'GET_PRODUCTS_DETAIL_FAILURE';


export const GET_PRODUCTS_SIMILAR_ITEM = 'GET_PRODUCTS_SIMILAR_ITEM';
export const GET_PRODUCTS_SIMILAR_ITEM_FAILURE = 'GET_PRODUCTS_SIMILAR_ITEM_FAILURE';

export const GET_USER_WISHLIST = 'GET_USER_WISHLIST';
export const GET_USER_WISHLIST_LOAD = 'GET_USER_WISHLIST_LOAD';
export const GET_USER_WISHLIST_FAIL = 'GET_USER_WISHLIST_FAIL';

export const POST_WISHLIST_ID='POST_WISHLIST_ID';
export const POST_WISHLIST_ID_FAIL='POST_WISHLIST_ID_FAIL';

export const DELETE_WISHLIST_ID='DELETE_WISHLIST_ID';
export const DELETE_WISHLIST_ID_FAIL='DELETE_WISHLIST_ID_FAIL';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';

export const EDIT_REVIEW = 'EDIT_REVIEW';
export const EDIT_REVIEW_FAIL = 'EDIT_REVIEW_FAIL';

export const GET_REVIEW = 'GET_REVIEW';
export const GET_REVIEW_FAIL = 'GET_REVIEW_FAIL';

export const CUSTOMER_REVIEW = 'CUSTOMER_REVIEW';
export const CUSTOMER_REVIEW_FAIL = 'CUSTOMER_REVIEW_FAIL';

export const GET_SEACRH_DATA = 'GET_SEACRH_DATA';
export const GET_SEACRH_DATA_FAILURE = 'GET_SEACRH_DATA_FAILURE';


export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';


export const GET_TRACKING_ORDER = 'GET_TRACKING_ORDER';
export const GET_TRACKING_ORDER_FAIL = 'GET_TRACKING_ORDER_FAIL';

export const GET_LISTING_PRODUCTS_LIST = 'GET_LISTING_PRODUCTS_LIST';
export const GET_LISTING_PRODUCTS_LIST_FAIL = 'GET_LISTING_PRODUCTS_LIST_FAIL';



export const GET_PRODUCTS_LIST_LOAD = 'GET_PRODUCTS_LIST_LOAD';
export const GET_LISTING_PRODUCTS_LIST_LOAD = 'GET_LISTING_PRODUCTS_LIST_LOAD';

export const GET_REGISTER_DATA_ERROR = 'GET_REGISTER_DATA_ERROR';







